// File recommented by recomment.cpp
// on Dec  9 2019 at 10:14:05.
//
// -*- mode: C; tab-width: 2 ; indent-tabs-mode: nil -*-
//
//  Universal Keyboard Project
//  ASDF firmware - small, fast, and simple keyboard encoder.
//
//  asdf.c
//
// This file contains code for:
// - the main scan code and key handler routines
// - key matrix declarations and keyboard state variables not delegated
//   elsewhere.
// - Key debouncing logic and data stuctures
// - dispatch of special functions bound to keys.
//
// Copyright 2019 David Fenyes
//
//  This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

#include "asdf.h"
#include "asdf_arch.h"
#include "asdf_ascii.h"
#include "asdf_buffer.h"
#include "asdf_hook.h"
#include "asdf_keymaps.h"
#include "asdf_modifiers.h"
#include "asdf_physical.h"
#include "asdf_repeat.h"
#include "asdf_virtual.h"
#include <stdint.h>
#include <stdio.h>

// The key scanner keeps track of the last stable (debounced) state of each key
// in the matrix, one bit per key, 8 bits per row.
static asdf_cols_t last_stable_key_state[ASDF_MAX_ROWS];

// Each key is debounced separately, supporting true N-key rollover, allowing a
// new key to be pressed when the previously pressed key is still debouncing.
// This requires a debounce counter for each key. This is is a large RAM
// footprint, 64 bytes for an 8 x 8 key matrix. It would be possible to only
// debounce the most recently pressed key and reduce the RAM usage to a single
// debounce counuter. However, this would probably require different handling of
// key presses and releases, and special handling for modifier keys, perhaps
// including separate debounce logic in the handlers for toggle keys such as
// CAPS_LOCK.
static uint8_t debounce_counters[ASDF_MAX_ROWS][ASDF_MAX_COLS];

// Stores the last key pressed
static asdf_keycode_t last_key;

// This is the handle for the char output buffer
static asdf_buffer_handle_t asdf_keycode_buffer;

// This is the handle for the message output buffer
static asdf_buffer_handle_t asdf_message_buffer;

// The delay time for strings sent via parallel port. This is needed because
// most keyboards have no handshaking, and we need to allow time for various
// environments to process the characters. Some, such as basic interpreters, are
// rather slow.  So we we allow keyboard modules to modifiy this delay.
static uint16_t asdf_print_delay_ms;

// PROCEDURE: asdf_put_code
// INPUTS: (asdf_keycode_t) code: code to be buffered for output
// OUTPUTS: none
//
// DESCRIPTION: Takes a keycode argument and buffers for output.
//
// SIDE EFFECTS: modifies buffer state.
//
// NOTES: If buffer is full, silently drop the code.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_put_code(asdf_keycode_t code) {
    asdf_buffer_put(asdf_keycode_buffer, code);
}

// PROCEDURE: asdf_putc
// INPUTS: (char) c: character to be buffered for output
//         (FILE *) stream - only used to match prototype.
// OUTPUTS: none
//
// DESCRIPTION: Takes a character generated by the system and buffers for
// output.
//
// SIDE EFFECTS: modifies buffer state.
//
// NOTES: If buffer is full, silently drop the code.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
int asdf_putc(char c, FILE *stream) {
    // for messages, add CR to LF:
    if ('\n' == c) {
        asdf_putc('\r', stream);
    }
    asdf_buffer_put(asdf_message_buffer, (asdf_keycode_t)c);
    return (int)c;
}

// PROCEDURE: asdf_next_code
// INPUTS: none
//
// OUTPUTS: (asdf_keycode_t) returns next value in buffer. If both buffers are
// empty, the code ASDF_INVALID_CODE is returned.
//
// DESCRIPTION: Checks the message buffer, and returns a character
// if present.  Otherwise, return the next code in the keycode
// buffer.
//
// SIDE EFFECTS: modifies buffer state.
//
// NOTES: A delay is enforced for system messages, to reduce the risk of dropped
// characters with unbuffered polling hosts. No delay is needed for typed
// keycodes, as these are generated at human speeds.
//
// SCOPE: public
//
// COMPLEXITY: 2
//
asdf_keycode_t asdf_next_code(void) {
    asdf_keycode_t code = asdf_buffer_get(asdf_message_buffer);
    if (ASDF_INVALID_CODE == code) {
        code = asdf_buffer_get(asdf_keycode_buffer);
    } else {
        // for system message
        asdf_arch_delay_ms(asdf_print_delay_ms);
    }
    return code;
}

// PROCEDURE: asdf_set_print_delay
// INPUTS: (uint8_t) delay_ms
//
// OUTPUTS: none
//
// DESCRIPTION: sets the delay to be used by the system print buffer
//
// SIDE EFFECTS: modifies character delay variable.
//
// NOTES: A delay is enforced for system messages, to reduce the risk of dropped
// characters with unbuffered polling hosts. No delay is needed for typed
// keycodes, as these are generated at human speeds.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_set_print_delay(uint8_t delay_ms) { asdf_print_delay_ms = delay_ms; }

// PROCEDURE: asdf_lookup_keycode
// INPUTS: row, col: specify a row and column in the keyboard matrix
// OUTPUTS: returns a keycode
//
// DESCRIPTION: Given a row and column in the keyboard matrix, returns the
// corresponding keycode, depending on the state of the modifier keys.
//
// SIDE EFFECTS: none
//
// NOTES:
//
// SCOPE: private
//
// COMPLEXITY: 1
//
asdf_keycode_t asdf_lookup_keycode(uint8_t row, uint8_t col) {
    return asdf_keymaps_get_code(row, col, asdf_modifier_index());
}

// Handler structure for unified dispatch table
typedef struct {
    void (*activate)(uint8_t param);
    void (*deactivate)(uint8_t param);
    uint8_t parameter;
    uint8_t flags; // Behavioral flags for the handler
} asdf_key_handler_t;

// Handler flags
#define ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT                                    \
    0x01 // Apply this action when initializing a keyboard

// PROCEDURE: asdf_emit_keycode
// INPUTS: keycode - the ASCII code to emit
// OUTPUTS: none
//
// DESCRIPTION: Handles activation of ASCII keycodes. Buffers the keycode for
// output and manages repeat state.
//
// SIDE EFFECTS: Updates last_key and repeat count
//
// SCOPE: private
//
// COMPLEXITY: 2
//
static void asdf_emit_keycode(uint8_t keycode) {
    asdf_put_code(keycode);
    if (last_key != keycode) {
        last_key = keycode;
        asdf_repeat_reset_count();
    }
}

// PROCEDURE: asdf_clear_last_keycode
// INPUTS: keycode - the ASCII code being released
// OUTPUTS: none
//
// DESCRIPTION: Handles deactivation of ASCII keycodes. Clears last_key if it
// matches the released keycode.
//
// SIDE EFFECTS: May clear last_key
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static void asdf_clear_last_keycode(uint8_t keycode) {
    if (last_key == keycode) {
        last_key = ACTION_NOTHING;
    }
}

// Unified dispatch table for all keycodes (ASCII and actions)
// This table maps every possible keycode value to its handler functions
static const asdf_key_handler_t asdf_handlers[256] = {
    // ASCII control characters (0x00 - 0x1F) using named constants for clarity
    [ASCII_NULL] = {.activate = asdf_emit_keycode,
                    .deactivate = asdf_clear_last_keycode,
                    .parameter = ASCII_NULL,
                    .flags = 0},
    [ASCII_SOH] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_SOH},
    [ASCII_STX] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_STX},
    [ASCII_ETX] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_ETX},
    [ASCII_EOT] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_EOT},
    [ASCII_ENQ] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_ENQ},
    [ASCII_ACK] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_ACK},
    [ASCII_BEL] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_BEL},
    [ASCII_BS] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_BS},
    [ASCII_TAB] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_TAB},
    [ASCII_LF] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_LF},
    [ASCII_VT] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_VT},
    [ASCII_FF] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_FF},
    [ASCII_CR] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_CR},
    [ASCII_SO] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_SO},
    [ASCII_SI] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_SI},
    [ASCII_DLE] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DLE},
    [ASCII_DC1] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DC1},
    [ASCII_DC2] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DC2},
    [ASCII_DC3] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DC3},
    [ASCII_DC4] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DC4},
    [ASCII_NAK] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_NAK},
    [ASCII_SYN] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_SYN},
    [ASCII_ETB] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_ETB},
    [ASCII_CAN] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_CAN},
    [ASCII_EM] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_EM},
    [ASCII_SUB] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_SUB},
    [ASCII_ESC] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_ESC},
    [ASCII_FS] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_FS},
    [ASCII_GS] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_GS},
    [ASCII_RS] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_RS},
    [ASCII_US] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = ASCII_US},

        // ASCII printable characters (0x20 - 0x7E)
        [' '] = {.activate = asdf_emit_keycode,
                 .deactivate = asdf_clear_last_keycode,
                 .parameter = ' '},
    ['!'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '!'},
    ['"'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '"'},
    ['#'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '#'},
    ['$'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '$'},
    ['%'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '%'},
    ['&'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '&'},
    ['\''] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = '\''},
    ['('] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '('},
    [')'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = ')'},
    ['*'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '*'},
    ['+'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '+'},
    [','] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = ','},
    ['-'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '-'},
    ['.'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '.'},
    ['/'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '/'},
    ['0'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '0'},
    ['1'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '1'},
    ['2'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '2'},
    ['3'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '3'},
    ['4'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '4'},
    ['5'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '5'},
    ['6'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '6'},
    ['7'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '7'},
    ['8'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '8'},
    ['9'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '9'},
    [':'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = ':'},
    [';'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = ';'},
    ['<'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '<'},
    ['='] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '='},
    ['>'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '>'},
    ['?'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '?'},
    ['@'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '@'},
    ['A'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'A'},
    ['B'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'B'},
    ['C'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'C'},
    ['D'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'D'},
    ['E'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'E'},
    ['F'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'F'},
    ['G'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'G'},
    ['H'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'H'},
    ['I'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'I'},
    ['J'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'J'},
    ['K'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'K'},
    ['L'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'L'},
    ['M'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'M'},
    ['N'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'N'},
    ['O'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'O'},
    ['P'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'P'},
    ['Q'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'Q'},
    ['R'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'R'},
    ['S'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'S'},
    ['T'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'T'},
    ['U'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'U'},
    ['V'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'V'},
    ['W'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'W'},
    ['X'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'X'},
    ['Y'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'Y'},
    ['Z'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'Z'},
    ['['] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '['},
    ['\\'] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = '\\'},
    [']'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = ']'},
    ['^'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '^'},
    ['_'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '_'},
    ['`'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '`'},
    ['a'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'a'},
    ['b'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'b'},
    ['c'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'c'},
    ['d'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'd'},
    ['e'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'e'},
    ['f'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'f'},
    ['g'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'g'},
    ['h'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'h'},
    ['i'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'i'},
    ['j'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'j'},
    ['k'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'k'},
    ['l'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'l'},
    ['m'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'm'},
    ['n'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'n'},
    ['o'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'o'},
    ['p'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'p'},
    ['q'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'q'},
    ['r'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'r'},
    ['s'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 's'},
    ['t'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 't'},
    ['u'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'u'},
    ['v'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'v'},
    ['w'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'w'},
    ['x'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'x'},
    ['y'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'y'},
    ['z'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = 'z'},
    ['{'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '{'},
    ['|'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '|'},
    ['}'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '}'},
    ['~'] = {.activate = asdf_emit_keycode,
             .deactivate = asdf_clear_last_keycode,
             .parameter = '~'},

    // DEL character
    [ASCII_DEL] = {.activate = asdf_emit_keycode,
                   .deactivate = asdf_clear_last_keycode,
                   .parameter = ASCII_DEL},

        // SOL-20 extended ASCII codes (0x80-0x9F)
        // These are special character codes used by the SOL-20 keyboard for
        // cursor movement, etc.
        [0x80] = {.activate = asdf_emit_keycode,
                  .deactivate = asdf_clear_last_keycode,
                  .parameter = 0x80}, // SOL_ASCII_MODE_SELECT
    [0x81] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x81}, // SOL_ASCII_LT_ARROW
    [0x82] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x82},
    [0x83] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x83},
    [0x84] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x84},
    [0x85] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x85},
    [0x86] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x86},
    [0x87] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x87},
    [0x88] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x88},
    [0x89] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x89},
    [0x8A] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8A},
    [0x8B] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8B}, // SOL_ASCII_CLEAR
    [0x8C] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8C}, // SOL_ASCII_LOAD
    [0x8D] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8D},
    [0x8E] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8E}, // SOL_ASCII_HOME
    [0x8F] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x8F},
    [0x90] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x90},
    [0x91] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x91},
    [0x92] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x92},
    [0x93] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x93}, // SOL_ASCII_RT_ARROW
    [0x94] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x94},
    [0x95] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x95},
    [0x96] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x96},
    [0x97] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x97}, // SOL_ASCII_UP_ARROW
    [0x98] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x98},
    [0x99] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x99},
    [0x9A] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9A}, // SOL_ASCII_DN_ARROW
    [0x9B] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9B},
    [0x9C] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9C},
    [0x9D] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9D},
    [0x9E] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9E},
    [0x9F] = {.activate = asdf_emit_keycode,
              .deactivate = asdf_clear_last_keycode,
              .parameter = 0x9F},

    // Action codes start at 0xA0 (ASDF_ACTION)
    // ACTION_NOTHING = 0xA0
    [ACTION_NOTHING] = {.activate = NULL, .deactivate = NULL, .parameter = 0},

    // Modifier actions - these affect keyboard state and should be reapplied on
    // init
    [ACTION_SHIFT] = {.activate = asdf_modifier_shift_activate,
                      .deactivate = asdf_modifier_shift_deactivate,
                      .parameter = 0,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_SHIFTLOCK_ON] = {.activate =
                                 asdf_modifier_shiftlock_on_activate,
                             .deactivate = NULL,
                             .parameter = 0,
                             .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_SHIFTLOCK_TOGGLE] =
        {.activate = asdf_modifier_shiftlock_toggle_activate,
         .deactivate = NULL,
         .parameter = 0,
         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_CAPS] = {.activate = asdf_modifier_capslock_activate,
                     .deactivate = NULL,
                     .parameter = 0,
                     .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_CTRL] = {.activate = asdf_modifier_ctrl_activate,
                     .deactivate = asdf_modifier_ctrl_deactivate,
                     .parameter = 0,
                     .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // Repeat control - affects keyboard state
    [ACTION_REPEAT] = {.activate = asdf_repeat_activate,
                       .deactivate = asdf_repeat_deactivate,
                       .parameter = 0,
                       .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // HERE_IS action (maps to USER_1 hook)
    [ACTION_HERE_IS] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                        .deactivate = NULL,
                        .parameter = ASDF_HOOK_USER_1},

    // Keymap selection - these are DIP switches that should be reapplied on
    // keyboard init
    [ACTION_MAPSEL_0] = {.activate = asdf_keymaps_map_select_set,
                         .deactivate = asdf_keymaps_map_select_clear,
                         .parameter = 0,
                         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_MAPSEL_1] = {.activate = asdf_keymaps_map_select_set,
                         .deactivate = asdf_keymaps_map_select_clear,
                         .parameter = 1,
                         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_MAPSEL_2] = {.activate = asdf_keymaps_map_select_set,
                         .deactivate = asdf_keymaps_map_select_clear,
                         .parameter = 2,
                         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_MAPSEL_3] = {.activate = asdf_keymaps_map_select_set,
                         .deactivate = asdf_keymaps_map_select_clear,
                         .parameter = 3,
                         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // Auto-repeat control - DIP switch setting
    [ACTION_AUTOREPEAT_SELECT] = {.activate = asdf_repeat_auto_on,
                                  .deactivate = asdf_repeat_auto_off,
                                  .parameter = 0,
                                  .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // Strobe polarity control - DIP switch setting
    [ACTION_STROBE_POLARITY_SELECT] =
        {.activate = asdf_arch_set_pos_strobe,
         .deactivate = asdf_arch_set_neg_strobe,
         .parameter = 0,
         .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // Virtual LEDs - reapply if toggle switches are pressed
    [ACTION_VLED1] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VLED1,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VLED2] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VLED2,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VLED3] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VLED3,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // Virtual outputs - reapply if toggle switches are pressed
    [ACTION_VOUT1] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT1,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VOUT2] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT2,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VOUT3] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT3,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VOUT4] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT4,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VOUT5] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT5,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},
    [ACTION_VOUT6] = {.activate = (void (*)(uint8_t))asdf_virtual_activate,
                      .deactivate = NULL,
                      .parameter = VOUT6,
                      .flags = ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT},

    // User function hooks
    [ACTION_FN_1] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_1},
    [ACTION_FN_2] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_2},
    [ACTION_FN_3] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_3},
    [ACTION_FN_4] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_4},
    [ACTION_FN_5] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_5},
    [ACTION_FN_6] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_6},
    [ACTION_FN_7] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_7},
    [ACTION_FN_8] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_8},
    [ACTION_FN_9] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                     .deactivate = NULL,
                     .parameter = ASDF_HOOK_USER_9},
    [ACTION_FN_10] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                      .deactivate = NULL,
                      .parameter = ASDF_HOOK_USER_10},
    [ACTION_FN_11] = {.activate = (void (*)(uint8_t))asdf_hook_execute,
                      .deactivate = NULL,
                      .parameter = ASDF_HOOK_USER_11},

    // Note: RESERVED actions are not handled
};

// PROCEDURE: asdf_activate_key
// INPUTS: keycode - the code for a key that has been pressed.
// OUTPUTS: none
//
// DESCRIPTION: Called when a key has been pressed. Uses a unified dispatch
// table to handle both ASCII keycodes and action codes with a single lookup.
//
// SIDE EFFECTS: Depends on the handler - ASCII codes update last_key and
// reset repeat timer. Action codes produce various side effects.
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static void asdf_activate_key(asdf_keycode_t keycode) {
    const asdf_key_handler_t *handler = &asdf_handlers[keycode];
    if (handler->activate) {
        handler->activate(handler->parameter);
    }
}

// PROCEDURE: asdf_deactivate_key
// INPUTS: keycode - the code for a key that has been released
// OUTPUTS: none
//
// DESCRIPTION: Called when a key has been released. Uses a unified dispatch
// table to handle both ASCII keycodes and action codes with a single lookup.
//
// SIDE EFFECTS: Depends on the handler - ASCII codes may clear last_key.
// Action codes produce various side effects.
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static void asdf_deactivate_key(asdf_keycode_t keycode) {
    const asdf_key_handler_t *handler = &asdf_handlers[keycode];
    if (handler->deactivate) {
        handler->deactivate(handler->parameter);
    }
}

// PROCEDURE: asdf_handle_key_press_or_release
// INPUTS: row, col: the row and column number of the key that has changed.
// OUTPUTS: none
//
// DESCRIPTION: Given a row and column of a key that has changed:
//
// 1) Debounce the key by decrementing a debounce timer. If not yet debounced,
//    return.
// 2) When the key is debounced, if the key is pressed, then call the activation
//    function associated with the key. Otherwise, if the key is released, call
//    the deactivation function for the key.
//
// SIDE EFFECTS: - Modifies debounce counter for the row and column
//               - After key debounces, modifies the table of stable key states
//               - Activate/deactivate functions have side effects
//
// NOTES:
//
// SCOPE: private
//
// COMPLEXITY: 3
//
static void asdf_handle_key_press_or_release(uint8_t row, uint8_t col,
                                             uint8_t key_was_pressed) {
    uint8_t *debounce_count = &debounce_counters[row][col];

    if (!(--(*debounce_count))) {

        // debounce timed out. Set new stable state and activate or

        // deactivate key.
        *debounce_count = ASDF_DEBOUNCE_TIME_MS;
        if (key_was_pressed) {
            last_stable_key_state[row] |= 1 << col;
            asdf_activate_key(asdf_lookup_keycode(row, col));
        } else {
            // key was released
            last_stable_key_state[row] &= ~(1 << col);
            asdf_deactivate_key(asdf_lookup_keycode(row, col));
        }
    }
}

// PROCEDURE: asdf_handle_key_held_pressed
// INPUTS: row, col: The row and column of a key that is being held down
// OUTPUTS: none
//
// DESCRIPTION: Given a row and column of a key that has been debounced and
// continues to be pressed:
// 1) Determine if this is the last key pressed.
// 2) If it's the most recent key, then check to see if it's time to repeat the
// key code. 3) If it's time to repeat, then do the repeat and reset the repeat
// timer.
//
// SIDE EFFECTS:
// - Causes repeat timer to tick, and may reset the repeat timer.
// - activate_key() will send a key code.
//
// NOTES: last_key is always a key code, never an action function, so only valid
// key codes will be repeated.
//
// SCOPE: private
//
// COMPLEXITY: 3
//
static void asdf_handle_key_held_pressed(uint8_t row, uint8_t col) {
    if (asdf_lookup_keycode(row, col) == last_key) {

        // if last debounced code-producing key is still pressed, handle repeat
        if (asdf_repeat()) {
            asdf_activate_key(last_key);
        }
    }
}

// PROCEDURE: asdf_keyscan
// INPUTS: none
// OUTPUTS: none
//
// DESCRIPTION: Scans the key matrix. For each row, read the columns and compare
// with last stable state. For each changed key, call a key-change handler
// function. For each stable pressed key, call a "continued press" handler
// function.
//
// SIDE EFFECTS:
//
// NOTES: 1) The keyboard state is stored as an array of words, with one word
//           per row, and each bit in a word representing one key in the row.
//
//        2) While it is tempting to use bit hacks to reduce the number of
//           cycles through the inner loop, I have opted to just loop over all
//           the bits (as long as there are some changed or pressed keys). For
//           an 8-bit word, bit tricks don't deliver much performance boost,
//           but do decrease code clarity.
//
// COMPLEXITY: 5
//
void asdf_keyscan(void) {
    asdf_cols_t (*row_reader)(uint8_t) =
        (asdf_cols_t(*)(uint8_t))asdf_hook_get(ASDF_HOOK_ROW_SCANNER);

    asdf_hook_execute(ASDF_HOOK_EACH_SCAN);
    for (uint8_t row = 0; row < asdf_keymaps_num_rows(); row++) {
        asdf_cols_t row_key_state = (*row_reader)(row);

        asdf_cols_t changed = row_key_state ^ last_stable_key_state[row];

        // loop over the bits until all changed or pressed keys in the row are
        // handled.
        for (uint8_t col = 0;
             /*(changed || row_key_state) && */ col < asdf_keymaps_num_cols();
             col++) {
            if (changed & 1) {
                // key state is different from last stable state
                asdf_handle_key_press_or_release(row, col, row_key_state & 1);
            } else if (row_key_state & 1) {
                asdf_handle_key_held_pressed(row, col);
            }
            changed >>= 1;
            row_key_state >>= 1;
        }
    }
}

// PROCEDURE: asdf_apply_all_actions
// INPUTS: none
// OUTPUTS: none
//
// DESCRIPTION: Scans the key matrix. For each row, read the columns, and for
// each bit, if an action is specified, then call the activate or deactivate
// function for that action, based on the key state. This is necessary to ensure
// that configuration settings, such as DIP switches and jumper settings, are
// properly handled when a keymap is changed.

// SIDE EFFECTS: See DESCRIPTION
//
// COMPLEXITY: 5
//
// SCOPE: private
//
void asdf_apply_all_actions(void) {
    for (uint8_t row = 0; row < asdf_keymaps_num_rows(); row++) {

        // Here we scan the last stable key state for each row. We don't rescan
        // because the map_select() functions interfere with the keymap change.

        asdf_cols_t row_key_state = last_stable_key_state[row];

        for (uint8_t col = 0; col < asdf_keymaps_num_cols(); col++) {
            if (row_key_state & 1) {
                asdf_keycode_t code = asdf_lookup_keycode(row, col);
                const asdf_key_handler_t *handler = &asdf_handlers[code];
                // Only apply handlers that should be reapplied on keyboard init
                if ((handler->flags & ASDF_HANDLER_APPLY_ON_KEYBOARD_INIT) &&
                    handler->activate) {
                    handler->activate(handler->parameter);
                }
            }
            row_key_state >>= 1;
        }
    }
}

// PROCEDURE: asdf_init
// INPUTS: none
// OUTPUTS: none
//
// DESCRIPTION: Reserve an output buffer to hold keycodes to be sent, and
// initialize the keyboard state and debounce counters
//
// SIDE EFFECTS: see DESCRIPTION
//
// SCOPE: public
//
// COMPLEXITY: 3
//
void asdf_init(void) {

    last_key = ACTION_NOTHING;

    asdf_buffer_init();  // initialize the buffers
    asdf_repeat_init();  // initialize the repeat counters
    asdf_keymaps_init(); // initialize keymaps. This also initializes the
                         // modifier key states.
    // reserve a buffer for the ASCII output:
    asdf_keycode_buffer = asdf_buffer_new(ASDF_KEYCODE_BUFFER_SIZE);
    asdf_message_buffer = asdf_buffer_new(ASDF_MESSAGE_BUFFER_SIZE);

    // Initialize all the keys to the unpressed state, and initialze the
    // debounce counters.
    for (uint8_t row = 0; row < ASDF_MAX_ROWS; row++) {
        last_stable_key_state[row] = 0;
        for (uint8_t col = 0; col < ASDF_MAX_COLS; col++) {
            debounce_counters[row][col] = ASDF_DEBOUNCE_TIME_MS;
        }
    }
}

//-------|---------|---------+---------+---------+---------+---------+---------+
// Above line is 80 columns, and should display completely in the editor.
